languageCode = "en-us"
title = "HOT Toolbox"
theme = "hotdocs"
DefaultContentLanguage = "en"
relativeurls = true
enableGitInfo = true

[params]
    DefaultContentLanguage = "en"
    GithubRepo = "https://github.com/hotosm/toolbox"
    SiteURL = "https://toolbox.hotosm.org"
    matomoSiteID = 16

[imaging]
    resampleFilter = "box"
    quality = 75

[languages]
  [languages.fr]
    contentDir = "content/fr"
    languageName = "Français"
    weight = 10
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 20
  [languages.es]
    contentDir = "content/es"
    languageName = "Español"
    weight = 20
